### ISSUE TITLE
How to create a channel?

### ISSUE THREAD

**Issue by schreiby** [zelloptt/zello-channel-api#124]
I saw that the API supports logging on to an existing channel but is there any support for creating a new channel, and if yes, can it be set to private, like a Zelect+ channel?

**Comment by vocoded** [comment]
Unfortunately there's no support in the channel API for creating new channels.  We will be focused on improving basic listening functionality next year, such as subscribing to multiple channels, before we take a look at management capabilities.

Thanks for your question!
