### ISSUE TITLE
Random "Channel is not ready" errors

### ISSUE THREAD

**Issue by TeaSeaLancs** [zelloptt/zello-channel-api#13]
Hi Zello team,

We've been doing an integration with your Javascript SDK and i've encountered a weird transient issue. I'm not sure how to reproduce it but I thought it was worth flagging up.

Every so often, even if there's nobody talking, when trying to send a message I get "Channel is not ready" errors sent back. The documentation indicates that this means that the channel is not online, and I should wait for an event to say that the channel is online. However, the channel _is_ online, i've already had that data come through, and there's nobody chatting on it.

Furthermore, when logged into the official Zello mobile app as another user, I can send messages through that fine.

Any help you could give in solving this would be greatly appreciated.

Cheers,
Matt.

**Comment by agatx** [comment]
Can you log all messages you are getting from the server when receiving this error and post the log (replace your channel /network name and any other sensitive data with dummy values)?

**Comment by TeaSeaLancs** [comment]
Unfortunately not as it was a transient error at the time and I didn't think to capture an exact log.

The approximate sequence of events was:

> Stream start
> Audio packet
> Audio packet
> Audio packet
< "Channel is not ready"
< "Channel is not ready"
< "Channel is not ready"
< Stream start response
> Audio packet
> Audio packet
< "Channel is not ready"
< "Channel is not ready"

**Comment by agatx** [comment]
Before you attempt stream start you need to receive status update from the channel with status online.  This should normally happen within seconds from connecting, assuming the channel name you provided is correct. 

Unrelated to this error but you should generally not attempt sending audio before you receive stream start response, because floor control is implemented on the channel side.

**Comment by TeaSeaLancs** [comment]
Hi @agatx,

The online status event had already been received at this point, plus the channel was, at the time, quiet.

The floor control and audio control information is useful to know however this was experienced while using your javascript SDK, so that should already be taken care of?

Anyway, this was a transient error, i've not experienced it since that one time, I just figured that since this occurred while using your SDK I would register it to help with the development :)

Cheers,
Matt.

**Comment by agatx** [comment]
Closing as it seems the issue didn't re-occur.
