### ISSUE TITLE
Getting "Cannot read property 'match' of null" on init - Javascript SDK

### ISSUE THREAD

**Issue by fayzaan** [zelloptt/zello-channel-api#16]
Hey,

I am trying to use the Javascript SDK in an angular app. I added the script tag with the url from the docs, but when trying to initialize:

```
ZCC.Sdk.init({
				player: true,
				recorder: true,
				encoder: true,
				widget: true
			})
				.then(function () {
					console.log('zcc.init.success')
				})
				.catch(function(err) {
					console.error('zcc.init.failed', err);
				})
```
an error is thrown from zcc.sdk.js Uncaught TypeError: Cannot read property 'match' of null. 

I looked deeper and it has to do with the getMyUrl method, getAttribute('src') may return null, it's not being handled.

**Comment by megamk** [comment]
@fayzaan can you please provide the minimal code to reproduce this issue, jsfiddle or codepin link will work, thank you. This issue looks like you are calling `ZCC.Sdk.init`  when `zcc.sdk.js` script is not yet loaded

**Comment by davidbelle** [comment]
I was able to replicate this problem by having a <script>....</script> tag before the call to zcc.sdk.js. 
IE.

```
<script>
  var hello = true;
</script>
<script src="https://zello.io/sdks/js/0.1/zcc.sdk.js"></script>
<script>
    // callback style
    ZCC.Sdk.init({
      player: true,  // true by default
      decoder: true, // true by default
      recorder: true, // true by default
      encoder: true, // true by default
    }, function(err) {
      if (err) {
        console.trace(err);
        return;
      }
      console.log('zcc sdk parts loaded')
    });

</script>
```

Removing the very first <script> fixes the problem.
