### ISSUE TITLE
README says max channel is 100 but can only connect to 5

### ISSUE THREAD

**Issue by davidbelle** [zelloptt/zello-channel-api#170]
Hi, 

My company has a zellowork account and based off the README page we should be able to authenticate on the websocket api for up to 100 channels. However if I try to authenticate with more than 5 I receive the "channels limit exceeded" error. 

I have used the CSharp example as a basis for my project.

Thanks

**Comment by vinnitu** [comment]
trying to connecto to only two channels but receive always "channels limit exceeded"

**Comment by Xxx000xxx9** [comment]
https://github.com/zelloptt/zello-channel-api/issues/170#issuecomment-1034842908

**Comment by Xxx000xxx9** [comment]
You might be able to code it to your preference using some copy paste but
be sure to use the correct code language

***@***.***
