### ISSUE TITLE
receiving audi from a particular user in Channel

### ISSUE THREAD

**Issue by ayush-pradhan-bit** [zelloptt/zello-channel-api#185]
I want to understand the code to send audio to a particular user in a channel and receive the audio from the other user.

**Comment by ayush-pradhan-bit** [comment]
Is it not possible to put a example for event to receive audio like it was for sending audio?

**Comment by vocoded** [comment]
The SDKs do include code to receive audio as well as send it, see for [example](https://github.com/zelloptt/zello-channel-api/blob/master/sdks/js/examples/01-player.html#L47). 

If you asking how to send a 1:1 message (user to user directly), that functionality is not currently supported by the API.
