### ISSUE TITLE
Timeout Error while receiving audio from another user in the channel

### ISSUE THREAD

**Issue by ayush-pradhan-bit** [zelloptt/zello-channel-api#186]
I have programmed the Events for On_stream_start. It detects the audio data but works only for 5 seconds- throwing an error of 
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

However, when I put timeout_sec to say 20. Program gets stuck and displays later receiving ended. 
[d5fbe9d11c7642095018dfefcce2a414.txt](https://github.com/zelloptt/zello-channel-api/files/8843310/d5fbe9d11c7642095018dfefcce2a414.txt)

**Comment by vocoded** [comment]
You should not wait on receiving socket data in this way. Websockets are always connected, even if they aren't sending or receiving data. You should define a handler to receive data when it arrives and process it as it becomes available.

Unfortunately we cannot provide detailed Python language support, please consult any of a number of online resources for more help.

**Comment by ayush-pradhan-bit** [comment]
I was able to  receive the data but they are in this form :

b"\x01\x00\x00zb\x00\x00\x00\x0fZh\xe1\xe2\x91\x0e\x8c\x17\xf1\xc2\xb4,\xae/\xbfu\t\x97c\x04b\xa1\xa7\xe4\xff!\xea\xfc\x01\x86\xbd\x0c\xb8\xc6hT\x1e\xdb\xcc\x18.T|\x98U\xecD\x10\x0c\x13E\xc6\xe6tQ/R\x8d\x11gv\xc8k\x14\x87j\x9b>x\t\x8e\xeelf\xd5\x11\xb4k\xc3\xfc\xda\xac\x0e\xcal\x15\x10$'k;\\\x86\xc2g\xbe\xe1^\xe58\xd0\x18\xc8\xeaU\xae\t\xc8x\xbb\xca\xe6\xc9t\xea\n\xd6\xd4A\x16\x16:O\x80'\xa1<\x17\xab>\xab\xc2\x04\xbd\xab.\x91\xb2\xc7\xe4\xb0\xef\xff\xccQ\xc8k45\xc3R\xb0\x7fR\xe6B\xda\x99\x904]\x19\x0c>\x99\xc5$p\xc0]N\xbeE\xf4\x1e\xa5\xac@\xa8lD\x12\x8ai\x01\xb3\x16P\r("

Is there any JS or any other code sample to decode this data?
