### ISSUE TITLE
Embedding Zello on a Website

### ISSUE THREAD

**Issue by 911BreakingNews** [zelloptt/zello-channel-api#194]
Hi everyone!
Would it be possible to embed Zello on a website so it would display and function like the desktop application?  I'd like to have Zello embedded on my personal website to be able to have 2 way communication with my friends and visitors to my website.  I am not sure what I need to do in order to accomplish this.  Would I just need to insert code into my website?  Or would I need to use the Zello API?  Any and all help is appreciated.  Thanks so much!

**Comment by vocoded** [comment]
Hi @911BreakingNews, apologies for our slow response. Yes, it is possible to embed Zello on a website to enable communication over a channel. It will require you to develop some custom code over our javascript SDK. Please take a look at the javascript examples in this repository for more information.
