### ISSUE TITLE
Connection Limits

### ISSUE THREAD

**Issue by tompierce** [zelloptt/zello-channel-api#21]
This is related to the closed issue: https://github.com/zelloptt/zello-channel-api/issues/15
I'm responding to @agatx 's comment:
> If your scenario requires rapid creation of connections from the same IP please contact us with details about what you are trying to accomplish.

One of the potential use cases for our integration is having a large number of users logging on and testing their Zello comms while all connected to the same wifi network (imagine a training course, or a briefing session or similar).

Because they are all on the same wifi network, their external IPs will be the same, and thus will share the 10 connections/minute/IP restrictions that are currently in place.

The issue is made worse by the JS SDK re-trying a failed connection multiple times. So if a user get's their password wrong, the login is retried until the connection limit is reached, which then blocks other users on the same wifi network.

Preventing retries in the event of bad credentials, and raising the limit to 50 requests/min/IP would probably avoid this issue for us in the foreseeable future.

Thanks,

Tom

**Comment by nayelizello** [comment]
Tom, this was changed to 50 per minute now. 

Thanks for explaining your use case.

**Comment by agatx** [comment]
Thanks for the detail, we changed to limit to 50 connection requests per minute per IP.
