### ISSUE TITLE
Reset password send recover not anymore

### ISSUE THREAD

**Issue by Allanksr** [zelloptt/zello-channel-api#224]
this works not anymore
https://zello.com/forgot_password/reminder_sent/
waiting already 3 days
If you didn't receive it within 15 minutes, check in your spam folder or [try again](https://zello.com/forgot_password/).
I did it

**Comment by vocoded** [comment]
There are a few reasons you may not receive a password reset email:

- Your email address is associated with more than 10 accounts
- You, or your email provider, previously marked a message from Zello as spam or suspicious
- Your email address is flagged with a likelihood of a bounceback
- Your email provider rejected the message

Please reach out to support@zello.com with your email address and we can see if there's any more detail on our end.
