### ISSUE TITLE
Getting "no phone" error on sending start_stream command

### ISSUE THREAD

**Issue by suhasHere** [zelloptt/zello-channel-api#23]
I am using zello-channel-api to build a python client and using it to listen in and also send audio to my channels of interest.

However, when i send the following start_stream command after successfully connecting to my channel

Done sending {'command': 'start_stream', 'seq': 2, 'type': 'audio', 'codec': 'opus', 'codec_header': 'gD4BPA==', 'packet_duration': 60}

I see the below response from the Zello Server
**server ... > {"error":"no phone","seq":2}**

How do i interpret this error ? and how do i get pass this error to be able to send audio packets from my python client to my channels.

**Comment by megamk** [comment]
Hello @suhasHere 
```
server ... > {"error":"no phone","seq":2}
```
This error means that channels that you're connecting to requires verified phone number for users to talk

**Comment by suhasHere** [comment]
@megamk  thanks much .. That helped a lot .. I am closing the issue. T
