### ISSUE TITLE
error: "no permission"

### ISSUE THREAD

**Issue by vinnitu** [zelloptt/zello-channel-api#29]
Hi!

I generate key, paste to 
![image](https://user-images.githubusercontent.com/432168/53902608-2ab87500-404a-11e9-9ca2-ee99ce4230f9.png)

but get in console

```
{command: "on_channel_status", channel: "Test", status: "offline", users_online: 0, error: "no permission", …}
```

**Comment by megamk** [comment]
Thank you for your report @vinnitu 
1) JS SDK option is named `listenOnly`
2) if you're setting `listenOnly` to `false` you need to provide valid `username` and `password` options. If you're setting it to `true` you can omit `username` and `password` but channel you're connecting to need to support anonymous listeners and channel `Test` does not
