### ISSUE TITLE
null

### ISSUE THREAD

**Issue by vinnitu** [zelloptt/zello-channel-api#31]
in my case (electon-vue) need to do fix

```javascript
if (src && src.match(/zcc.sdk\.js$/)) { 
```

https://github.com/zelloptt/zello-channel-api/blob/a280728281b5be7aac531e3e00b20a85aef4e3c1/sdks/js/src/classes/sdk.js#L141

**Comment by megamk** [comment]
Not clear what your problem is. JS SDK works in Electron environment, since browser-based, you don't need to `require` sdk files in JS context, add it with `script` tag on your html page and `ZCC` will be available in the Electron's renderer process

**Comment by vinnitu** [comment]
I think it linked with https://github.com/zelloptt/zello-channel-api/issues/16
