### ISSUE TITLE
Please clarify expected data format for outgoing audio stream

### ISSUE THREAD

**Issue by rl1987** [zelloptt/zello-channel-api#34]
Hello,

I am working on a Python script that would allow pushing audio files into Zello channel. However it is unclear to me how to convert the audio data into the format that Zello would accept. 

1) What are the semantics of `codec_header` and `packet_duration` fields in `start_stream` request?
2) What exactly is expected in payload of streamed data packet? I tried setting `packet_duration` to 200 milliseconds, like it was in the documentation example and passing 200 ms long Ogg file, but that didn't work - probably because Ogg is container format that wraps Opus format within. However, how do I get the exact data that Zello server expects to receive? I looked at [RFC7845](https://tools.ietf.org/html/rfc7845.html) and suspect that maybe it's Ogg audio data page payload, but I'm not sure?

Is there a way to use ffmpeg or some other tooling to convert arbitrary audio data in a format that Zello server can accept?

**Comment by ekavun** [comment]
Hello,
Can anybody provide an update on this?
From your support, I get the feeling that Zello is only interested in Zello Work or Zello Enterprise integrations. You have an API out there, so unless you're only working on appearances, it would be nice if somebody could address this issue. Seems pretty trivial.

Thanks!

**Comment by OnkelTem** [comment]
@rl1987 @ekavun  
Guys, have you managed to do it?
My friend is working on this and also have problems with understanding how to use all this.

It is shame actually that then never replied on this.

**Comment by megamk** [comment]
Sorry for long response times.

> What are the semantics of codec_header and packet_duration fields in start_stream request?

`codec_header` is built like this ([example from js sdk](https://github.com/zelloptt/zello-channel-api/blob/409378acd06257bcd07e3f89e4fbc885a0cc6663/sdks/js/src/classes/utils.js#L60-L67)):
 It's a base64 encoded 4 byte string: first 2 bytes for sample rate, 3rd for number of frames per packet (1 or 2), 4th for the frame size

> What exactly is expected in payload of streamed data packet? 

Payload is described here: https://github.com/zelloptt/zello-channel-api/blob/master/API.md#stream-data
And yes, this has to be opus data, not wrapped with ogg container.  
As mentioned [here](https://github.com/zelloptt/zello-channel-api/issues/33), 200ms was the documentation error

**Comment by vocoded** [comment]
Please see example code here:

https://github.com/zelloptt/zello-channel-api/tree/master/examples
