### ISSUE TITLE
Widget state becomes invalid when connection is interrupted

### ISSUE THREAD

**Issue by agatx** [zelloptt/zello-channel-api#35]
![image](https://user-images.githubusercontent.com/19314549/54807376-07e1af80-4c4b-11e9-9bd3-e899b37ca3f3.png)

I had a page with the widget opened, then closed the laptop lid.
When I opened it 2+ hours later the indication was showing an active message with 2:30 hours play time, and counting.

**Comment by megamk** [comment]
fix deployed
