### ISSUE TITLE
Not working or am I missing something ?

### ISSUE THREAD

**Issue by nmaniatis** [zelloptt/zello-channel-api#44]
Dear Zelloptt,

I have downloaded the ZelloChannelKit for iOS and install into 2 devices the ZellochanelDemo app.
I added my development token and logged in as driver from the first device and as rider in the second. Unfortunately I couldn't make any communication, as the messages don't appear to be playing in either device. 

Also in an example I tried, but the session.startVoiceMessage() function always returns nil. 
Both devices have accepted the microphone usage.

Thanks.

**Comment by cooksey** [comment]
Hi, can you verify that you have created the channel that you are trying to connect to, and that both users are members of the channel already?
