### ISSUE TITLE
[JS][Doc] How to send mp3/wav to a channel?

### ISSUE THREAD

**Issue by OnkelTem** [zelloptt/zello-channel-api#53]
I create this new issue as a stub for those looking for the same base thing as I do. 
Let's keep it simple: **how to send an mp3/wav/ogg file to a channel?**

Sending a prerecordered message [example from this repo](https://github.com/zelloptt/zello-channel-api/blob/master/sdks/js/examples/06-send-pre-recorded.html) kind of lacks the part were we pick the file itself. It's not actually clear what those fancy digits mean.

Thanks in advance!

**Comment by megamk** [comment]
> It's not actually clear what those fancy digits mean.

Those are opus packets. 
To send files you need to override Recorde with a custom recorder. See [this sample](https://github.com/zelloptt/zello-channel-api/blob/44e8aa6e2ba158ffc58ef8439f651bc976ab85f0/sdks/js/examples/05-custom-recorder-echo.html)


It sends incoming messages back to the channel using custom recorder. You need to implement your own customrecorder that will be getting pcm data from your source

**Comment by OnkelTem** [comment]
@megamk 

Thanks for the link. Regarding that sample, why the audio it's sending back is played at a slower speed  and lower pitch? To my ear - the pitch is lower by 5th (in musical terms).

**Comment by megamk** [comment]
> Thanks for the link. Regarding that sample, why the audio it's sending back is played at a slower speed and lower pitch? To my ear - the pitch is lower by 5th (in musical terms).

it shouldn't be like that. Which device and app version are you using to send initial audio?

**Comment by vocoded** [comment]
Please see our extended examples here:

https://github.com/zelloptt/zello-channel-api/tree/master/examples
