### ISSUE TITLE
How to be connected in multiple channels in same time?

### ISSUE THREAD

**Issue by ihrupin** [zelloptt/zello-channel-api#60]
Dear support,

My app has to be able to listen to multiple channels at the same time.
It is similar to the Zello app from AppStore.
How can I implement it in my app?

**Comment by OnkelTem** [comment]
I join the author, is it possible to connect to several channels at the same time?

**Comment by ZenFeedbacker** [comment]
Same issue here. The API specification states that:

> Connecting to multiple channels (up to 100) is currently supported for Zello Work only.

Are there any plans on implementing this for Consumer Zello?

**Comment by vocoded** [comment]
@ZenFeedbacker There are no current plans but I think this is something we will eventually support. We will keep this ticket updated with any change in status.

**Comment by ZenFeedbacker** [comment]
@vocoded  thanks! So I suppose the workaround is run a different process with a different ip & port for each channel?

**Comment by 108w6war** [comment]
Guys I have a question I have 3 channels connected together through rf radio that talks to all the channels at the same time.
The issue I am having is if an app user talks on one channel the other two can hear it is there anyway to link them all together so that the all work together at the same time

**Comment by agatx** [comment]
Zello Channel API now support connecting to multiple channels, you just need to pass the list of channel names in `channels` parameter of the `logon` call https://github.com/zelloptt/zello-channel-api/blob/master/API.md#logon-1
