### ISSUE TITLE
PCM Data

### ISSUE THREAD

**Issue by arsen3d** [zelloptt/zello-channel-api#66]
Would you please create an example for proper way to take a voice data stream so that it can be sent to api or saved to disk.
```
 var GpcmData=[];
          session.on('incoming_voice_data_decoded', function(pcmData, incomingMessage) {
            GpcmData.push(pcmData);
            if (!showIncomingDataChunks()) {
              return;
            }
            appendLog(`<b>incoming_voice_data_decoded</b> id: <b>${incomingMessage.instanceId}</b>, data: ${pcmData.length} bytes`);
          });
```

**Comment by vocoded** [comment]
We have released new sample audio send code in several languages - https://github.com/zelloptt/zello-channel-api/tree/master/examples

Saving audio data depends heavily on local requirements (output medium, format, etc) and thus is not as well suited to generic examples.
