### ISSUE TITLE
Clarification on stream data packets

### ISSUE THREAD

**Issue by tompierce** [zelloptt/zello-channel-api#8]
Hi Zello Team,

I've been creating a basic browser client using the channel API. Login and receiving channel status is working nicely, but I'm having some trouble playing the audio in the stream data packets that are received.
My main source of reference is this section of `API.md`:

> Stream data
> The same packet structure is used for any streamed data (e.g. audio) travelling both ways. The packet ID field is only used with the audio packets sent from the server to a client. Fields are stored in network byte order.
> ```
> {type(8) = 0x01, stream_id(32), packet_id(32), data[]}
> ```

But I'm not sure how I should be parsing the data received via the `onmessage` callback on my websocket:

```
...

websocket = new WebSocket("wss://zello.io/ws");

websocket.onopen = function() {
  print("Connection initialised...");
}

websocket.onclose = function() {
  print("Connection closed...");
}

websocket.onerror = function(error) {
  print("Connection Error: " + error);
}

websocket.onmessage = function(event) {
  if (event.data instanceof Blob) {
    // extract audio somehow?
    audio_bytes = ??? event.data ???
    audio_buffer.push(audio_bytes);
  } else {
    console.log(event.data);
  }
}

...

```

Should I just be dropping the first 72 bytes (8 + 32 + 32) and appending to the buffer, or have I misunderstood? Any extra detail/example code would be most appreciated.

**Comment by agatx** [comment]
The audio packet header is 72 bits = 9 bytes. So if you strip first 9 bytes, the remainder will be audio packet data encoded with [opus](http://opus-codec.org/)

We are working on Javascript SDK which will give you all the code needed to decode and play incoming audio.

**Comment by tompierce** [comment]
Thanks for clearing that up. Can each packet be decoded independently, or must we buffer a certain amount before decoding?

I've pulled out the relevant bits of my code below, which attempts to decode each packet and then append to an AudioBuffer - but I get `DOMException: Unable to decode audio data` in Chrome v66 (and similar in Firefox).

```
var reader       = new FileReader();
var websocket    = new WebSocket("wss://zello.io/ws");
var audioCtx     = new (window.AudioContext || window.webkitAudioContext)();
var audio_buffer = audioCtx.createBuffer(1, 1 * audioCtx.sampleRate, audioCtx.sampleRate);

// strip the header and decode the opus audio
// then append to the audio buffer
reader.onload = function(e) {
  console.log("Packet received. Size: ", reader.result.byteLength, " bytes");
  header_removed = reader.result.slice(9)
  audioCtx.decodeAudioData(header_removed, function(buffer) {
    audio_buffer = appendBuffer(audio_buffer, buffer);
  }, function(e){
    console.error(e)
  });
}

// listen for audio stream blobs on the web socket
websocket.onmessage = function(event) {
  if (event.data instanceof Blob) {
    reader.readAsArrayBuffer(event.data)
  } else {
    print(event.data);
  }
}
```

How far from ready is the Javascript SDK? We've been asked about integrating Zello into our own mobile and web apps, so it would definitely be useful. I'd be happy to test out an alpha version?

**Comment by agatx** [comment]
Javascript SDK ETA is the end of the next week.

**Comment by tompierce** [comment]
Awesome. 
FYI, we managed to setup basic web app that could listen in to a channel, playing back the audio as soon as it was available. But we will wait for the javascript SDK before doing any further integration work.

Thanks for your help.
